feat: support negative pattern matching
ericpromislow/tabhunter pull request #132
Opened 2024-10-09 10:20 UTC by dnwe

Allow the use of a `!` prefix to invert the matching behaviour in tabhunter. For example, a pattern of `!github.com` will match any tab that does not contain github.com in either the title or url.

2024-10-14 18:39 UTC, ericpromislow requested changes
This isn't the right way, because both tab titles and URLs can contain `!`s, and should be searchable as is. But there is one meta-pattern that has been supported for a long time, and that's when a pattern starts with `{w:<NUMBER>[-<NUMBER>]?}<PATTERN>`.  This looks for patterns only in window #X, or windows #X-Y.

So what about adding a `{!:}`? The wrinkle here is that if more meta-directives are added in the future, order shouldn't matter. Which means you'll need to handle both `{w:...}{!:}PATTERN` and `{!:}{w:...}PATTERN`. I would do this in a loop at the start of `buildMatchedItemsArray` to allow these in either order (allow duplicates, where the last one wins), so by the time you enter the `try` block you have your `winFnParts` function array and `negate` set in advance.

I would stay away from doing this through a checkbox. Feedback over the years show many tabhunber users prefer to keep their hands on the keyboard (of course).

2024-10-14 18:55 UTC, ericpromislow commented
I merged in the 3 housekeeping-related changes, but they shouldn't cause any user-visible changes, so I ignored them (I'm not sure how that `undefined` glitch manifests itself as a bug). Pushing new bits to both firefox and chrome take a while, so I'll wait until either of the two remaining PRs is ready for merging. One of them should be version 3.6.4, and the other 3.6.5 (assuming no other changes go in).

Thanks for doing all this!

2024-10-14 21:46 UTC, dnwe commented
Note: that `!` is only used to invert if its the first character in the pattern box. So when you explicitly want to search for a `!` in title or url, that is still possible by escaping or adding a `.` beforehand

e.g.,

<img width="606" alt="image" src="https://github.com/user-attachments/assets/7e71abb3-3b80-4672-9f30-96c3705a3cd7">
<p>
<p>
I thought it would generally be a rarer case that someone needed to match tabs on `!` alone, compared with what seemed like a more readily useful usecase of being able to filter out one or more patterns, so I was keen to provide that in the simplest and/or most discoverable form if we can

2024-10-16 19:08 UTC, ericpromislow commented
I thought of that, but would rather use the existing meta-pattern syntax to do meta stuff. True, there's only one meta-pattern right now, but I'd rather scale it up in the direction I outlined. 

Also keep in mind that tabhunter works without regexes, so I imagine many users actually aren't familiar with backslash-escaping.

2024-10-16 22:56 UTC, dnwe commented
@ericpromislow ok no worries, I've pushed up a commit with the behaviour I think you were asking for. I changed the code to allow the meta-directive to be anywhere in the pattern before applying it and stripping it out and kept things simple with that rather than looping until I can't find more meta-directives. It won't account for people writing multiple versions of the same directives, but I think it's probably reasonable to just ignore misbehaviour and keep the code simple?

2024-11-11 22:39 UTC, ericpromislow approved these changes
Looks good - thx

2024-11-11 22:39 UTC, merged